services:
  kusto-query-cli:
    build: .
    image: kusto-query-cli:${KUSTO_QUERY_CLI_VERSION}
    volumes:
      - type: bind
        source: ./queries
        target: /usr/src/app/queries
      - type: volume
        source: kusto-query-cli-azure-state
        target: /root/.azure
    entrypoint: ["/usr/src/app/entrypoint.sh"]
volumes:
    kusto-query-cli-azure-state:
